# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plexos', '0002_auto_20180322_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to=b'')),
            ],
        ),
    ]
