# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plexos', '0003_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_file',
            name='url',
            field=models.FileField(upload_to='files/%Y/%m/%d'),
        ),
    ]
